nguage: ruby
rvm:
- 2.3.1
install:
- bundle install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: dbc46d612394fb09243deb193b03a29046e3c237
  local_dir: _site
  target_branch: master
  on:
    branch: source
